# Generated by Django 6.0.4 on 2026-04-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competencias", "0001_initial"),
        ("licenciatura", "0001_initial"),
        ("tecnologias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video_demo_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField()),
                ("competencias", models.ManyToManyField(to="competencias.competencia")),
                ("tecnologias", models.ManyToManyField(to="tecnologias.tecnologia")),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenciatura.unidadecurricular",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projetos",
            },
        ),
    ]
