# Generated by Django 6.0.4 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField(blank=True)),
                ("erros_correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "foto_papel",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
            options={
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
    ]
