# Generated by Django 6.0.4 on 2026-04-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenciatura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=150)),
                ("resumo", models.TextField()),
                ("ano", models.PositiveIntegerField()),
                ("destaque", models.BooleanField(default=False)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenciatura.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TFCs",
            },
        ),
    ]
