# Generated by Django 6.0.4 on 2026-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfcs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="licenciatura",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="resumo",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciaturas",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.TextField(blank=True),
        ),
    ]
