# Generated by Django 6.0.4 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("nivel", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Competências",
            },
        ),
    ]
