# Generated by Django 6.0.4 on 2026-04-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("nivel", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("pagina_pessoal_url", models.URLField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=10)),
                ("descricao", models.TextField()),
                ("duracao_anos", models.PositiveIntegerField()),
                ("ects_total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("website_oficial", models.URLField(blank=True)),
                ("nivel_preferencia", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=150)),
                ("resumo", models.TextField()),
                ("ano", models.PositiveIntegerField()),
                ("destaque", models.BooleanField(default=False)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trabalhos Finais de Curso (TFCs)",
            },
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("ano_curricular", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                ("docentes", models.ManyToManyField(to="portfolio.docente")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video_demo_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField()),
                ("competencias", models.ManyToManyField(to="portfolio.competencia")),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projetos",
            },
        ),
    ]
