# Generated by Django 6.0.4 on 2026-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("instituicao", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("certificado_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Formações",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField(blank=True)),
                ("erros_correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "foto_papel",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
            options={
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name_plural": "TFCs"},
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="licenciatura",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="resumo",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="descricao",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciaturas",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="apresentacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="natureza",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="portfolio.docente"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
