# Generated by Django 6.0.4 on 2026-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_tecnologia_tfc_unidadecurricular_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=150)),
                ("curso", models.CharField(max_length=150)),
                ("ano_inicio", models.PositiveIntegerField()),
                ("ano_fim", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Formações",
            },
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="interesses/"),
                ),
            ],
            options={
                "verbose_name_plural": "Interesses",
            },
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name_plural": "TFCs"},
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="video_demo_url",
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
    ]
