# Generated by Django 6.0.4 on 2026-04-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_tecnologia_tfc_unidadecurricular_projeto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="competencias",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="docentes",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="licenciatura",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="licenciatura",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="tecnologias",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="unidade_curricular",
        ),
        migrations.DeleteModel(
            name="Competencia",
        ),
        migrations.DeleteModel(
            name="Docente",
        ),
        migrations.DeleteModel(
            name="Licenciatura",
        ),
        migrations.DeleteModel(
            name="TFC",
        ),
        migrations.DeleteModel(
            name="Tecnologia",
        ),
        migrations.DeleteModel(
            name="Projeto",
        ),
        migrations.DeleteModel(
            name="UnidadeCurricular",
        ),
    ]
