# Generated by Django 6.0.4 on 2026-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_formacao_interesse_alter_tfc_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="imagem_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
