# Generated by Django 6.0.4 on 2026-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tfc_imagem_url_tfc_link_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="codigo_curso",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo_uc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="conteudo_programatico",
            field=models.TextField(blank=True, null=True),
        ),
    ]
