# Generated by Django 6.0.4 on 2026-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_licenciatura_codigo_curso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formacao",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="formacao/"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="ano",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="link_youtube",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
