# Generated by Django 6.0.4 on 2026-04-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docentes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=10)),
                ("descricao", models.TextField()),
                ("duracao_anos", models.PositiveIntegerField()),
                ("ects_total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("ano_curricular", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                ("docentes", models.ManyToManyField(to="docentes.docente")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenciatura.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
    ]
