# Generated by Django 6.0.4 on 2026-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docentes", "0001_initial"),
        ("licenciatura", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="descricao",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="apresentacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="natureza",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="docentes.docente"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
