# Generated by Django 6.0.4 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("website_oficial", models.URLField(blank=True)),
                ("nivel_preferencia", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Tecnologias",
            },
        ),
    ]
